### ISSUE TITLE
ChangeWidth

### ISSUE THREAD

**Issue by qcfer35** [pnikosis/materialish-progress#10]
As changing the width ProgressWheel?

                              <com.pnikosis.materialishprogress.ProgressWheel
                                android:id="@+id/progress_wheel"
                                android:layout_width="200dp"
                                android:layout_height="200dp"
                                android:layout_gravity="center_horizontal"
                                app:barColor="@color/colorPrimary"
                                app:progressIndeterminate="true"
                                />

has the same effect that is with 80dp

                              <com.pnikosis.materialishprogress.ProgressWheel
                                android:id="@+id/progress_wheel"
                                android:layout_width="80dp"
                                android:layout_height="80dp"
                                android:layout_gravity="center_horizontal"
                                app:barColor="@color/colorPrimary"
                                app:progressIndeterminate="true"
                                />

![screenshot_2015-01-02-10-54-42](https://cloud.githubusercontent.com/assets/5713697/5597765/f0fd8a1e-926d-11e4-9149-ee92b3998b19.png)

app: rimWidth does not have any effect

**Comment by pnikosis** [comment]
Change the color of the rim for checking the rimWidth. From your screenshot, looks you have a transparent rim (maybe you want to check the barWidth property)

**Comment by pnikosis** [comment]
Also, you are changing the size of the layout, not the size of the wheel. If you want the wheel to fill up the layout, use
