### ISSUE TITLE
Prefix all attributes with something to avoid collisions

### ISSUE THREAD

**Issue by pankajbatra** [pnikosis/materialish-progress#11]
I am trying to use sweet alert dialog(which is dependent on this lib) with another library and on gradle compile, I receive following error.
Error:Attribute "barColor" has already been defined

Can you please prefix all attributes with name like matProg_ so that they never clash with any other names.

**Comment by onewilk** [comment]
@pankajbatra good point ! @pnikosis just do it

**Comment by Kuratkoo** [comment]
+1

**Comment by pnikosis** [comment]
You are right. Great suggestion, I'll do it ASAP.

**Comment by pankajbatra** [comment]
Please upload new version on Maven too.
https://maven-repository.com/artifact/com.pnikosis/materialish-progress

**Comment by pnikosis** [comment]
Already uploaded, takes a while though.

**Comment by diwakersurya** [comment]
Sweet Alert Dialog uses materialish progress library which contains ic_launcher icon in its drawables. While building my project, I got duplicate ic_launcher error . Please Fix the issue.
