### ISSUE TITLE
StartActivity blocking UI and animation

### ISSUE THREAD

**Issue by ppamorim** [pnikosis/materialish-progress#12]
Hi, I've a app with this library and I found some issues with UI, it's happens (the progress) before when the app start a new activity or another anything that use more processing, even within the asynchronous class.
Anyone can help me?

**Comment by cuixbo** [comment]
i have the same problem, the progress looks like be blocked by some operations in UI thread

**Comment by pnikosis** [comment]
Probably fixed, check https://github.com/pnikosis/materialish-progress/issues/13
