### ISSUE TITLE
Wheel is slow or choppy after returning to activity

### ISSUE THREAD

**Issue by omegavesko** [pnikosis/materialish-progress#13]
After returning to the activity from another activity or the launcher, I've noticed that the progress wheel becomes slow or choppy for a while, and then returns to normal. This is on a Nexus 5 running Lollipop. 

Is this something wrong with my code, or can you guys reproduce it as well?

**Comment by pnikosis** [comment]
Can you provide some code to reproduce it?

**Comment by vivekkartha** [comment]
I also have the same issue, the issue gets reproduced when u shuffle between activities that use the wheel many times.

**Comment by androlizer** [comment]
i used to have this issue, then i get to know that I should call `spin()` to let it work normally, Though it'll make rounds even you don't call `spin()` but it's not the correct approach, I think it might help.

**Comment by pnikosis** [comment]
OK, that last comment maybe could give me a clue about what going on, I'll investigate this further.

**Comment by androlizer** [comment]
this issue is somewhat related to this https://github.com/pnikosis/materialish-progress/issues/9#issuecomment-69759983, which i opened

**Comment by pnikosis** [comment]
I just pushed a change that maybe fixes this issue, I'm closing it, but feel free to reopening it if you still find the issue. Just be sure that you are using v1.5

**Comment by androlizer** [comment]
@pnikosis have you updated the artifact if so, please update the ReadMe. Thanks.

**Comment by pnikosis** [comment]
You are right, updated
