### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by paul321** [pnikosis/materialish-progress#14]
Hello

Im trying to include this library in my project and there is no way a can compile it, it doesn't recognize R.stylable and all the other properties like

R.styleable.ProgressWheel_matProg_fillRadius
R.styleable.ProgressWheel_matProg_barWidth
R.styleable.ProgressWheel_matProg_rimWidth

Am i doing something wrong?

**Comment by pnikosis** [comment]
Try with

compile 'com.pnikosis:materialish-progress:1.3'

In your gradle file (not 1.2).

**Comment by fbis251** [comment]
Hey @pnikosis I have also tried to include your library in a brand new project, used the dependency, example XML and java lines from the README. Once I compile the layout is showing me that the wheel gets instantiated but the layout doesn't have anything inside it or is invisible.

![bug](https://cloud.githubusercontent.com/assets/1300530/5835464/d88af3fe-a11d-11e4-9fb8-b0964c24c3a8.png)

It basically looks like that once I compile and run the app on my device. Just a blank space

**Comment by pnikosis** [comment]
It is normal to see a blank space in the layout view. Probably I should put something in edit mode.

**Comment by fbis251** [comment]
The device also only displays a blank box, exactly as it displays on the layout editor. I can take a screenshot of the device for you.

**Comment by pnikosis** [comment]
Sorry if it is a stupid question, but have you set the progress as indeterminate? (or set a progress value)

Also, what's the rIm width? and color? have you override them?

**Comment by fbis251** [comment]
Okay I made a little progress by reverting back to version 1.2. Version 1.3 is not recognizing the wheel: prefix and I am unable to style the wheel using XML only.

With 1.2 I can control the wheel both with XML (using the wheel prefix) and Java.

``` XML
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                xmlns:wheel="http://schemas.android.com/apk/res-auto"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                tools:context=".MainActivity">

    <com.pnikosis.materialishprogress.ProgressWheel
            android:id="@+id/progress_wheel"
            android:layout_width="80dp"
            android:layout_height="80dp"
            wheel:barColor="#00ff00"
            wheel:progressIndeterminate="true"/>
</RelativeLayout>
```
Again, the above XML works fine with 1.2 but not 1.3

**Comment by fbis251** [comment]
Alright I found the issue, I was using the example in the README which doesn't use the updated prefixes. Once I used the updated prefixes I no longer have an issue.

I opened a pull request to update the README
https://github.com/pnikosis/materialish-progress/pull/15

Thanks for your awesome library!

**Comment by Sradhenduway** [comment]
i m new in android . i want to use sweet alert dialog but i having error.when i try to sync.

"Unable to resolve dependency for ':library@debug/compileClasspath': Could not resolve com.pnikosis:materialish-progress:1.0.

Could not resolve com.pnikosis:materialish-progress:1.0.
Required by:
    project :library
 > No cached version of com.pnikosis:materialish-progress:1.0 available for offline mode."
