### ISSUE TITLE
jcenter and mavenCentral have different artifact for version 1.4

### ISSUE THREAD

**Issue by alexvasilkov** [pnikosis/materialish-progress#18]
Hi, thank you for good work!

I encountered a strange issue. Version 1.4 of this library is different when using jcenter() repository and mavenCentral() repository. [First repo](https://bintray.com/bintray/jcenter/com.pnikosis%3Amaterialish-progress/1.4/view) contains version from January 22 where ProgressCallback uses double parameter, while [second repo](http://search.maven.org/#artifactdetails%7Ccom.pnikosis%7Cmaterialish-progress%7C1.4%7Caar) contains version from January 26 where ProgressCallback uses float parameter. So when you changing from one repo to the other project starts failing to compile.

It may not be a big deal, but for unknown reasons my Jenkins installation loads artifacts from jcenter, while local machine uses maven central (which is specified in build.gradle).

Could you please align versions in both repos? Or is it out of your control?

**Comment by pnikosis** [comment]
I can push the version to 1.4.1 to force both to be updated. Not the prettiest solution, but I thing it should work.

**Comment by alexvasilkov** [comment]
Yes, it would be great! Thanks

**Comment by pnikosis** [comment]
Updated and fixed
