### ISSUE TITLE
Request - Color Change

### ISSUE THREAD

**Issue by TurKurT656** [pnikosis/materialish-progress#19]
Hi Bro,
This is great lib that I've seen for progress bar.
Can u make it like Gmail application (color changes every time circle spin completes).

Sorry for my bad English.
ThnQ

**Comment by pnikosis** [comment]
Hi there

You can use the ProgressCallback for this. In indeterminate mode, the callback gets called every time the wheel is shrinked (completing a turn), so you can change the color in that moment.
