### ISSUE TITLE
Adding in code not working

### ISSUE THREAD

**Issue by rajohns08** [pnikosis/materialish-progress#21]
When I add a ProgressWheel in code with:

    ProgressWheel loadingDialog = new ProgressWheel(context);
    loadingDialog.spin()

nothing happens.

**Comment by brucewuu520** [comment]
me too, are you solve?

**Comment by rajohns08** [comment]
No, I just used the xml code

**Comment by brucewuu520** [comment]
i solve it, you must setLayoutParams  with width and height

**Comment by rajohns08** [comment]
I tried:

    ProgressWheel loadingWheel = new ProgressWheel(this);
    RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(60, 60);
    loadingWheel.setLayoutParams(layoutParams);
    loadingWheel.setBarColor(Color.GREEN);
    loadingWheel.spin();

but it still doesn't work for me.

**Comment by gunhansancar** [comment]
rajohns08 you have to add progresswheel to some view after that it can be visible.

            RelativeLayout.LayoutParams params = new   RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.MATCH_PARENT);
            params.addRule(RelativeLayout.CENTER_IN_PARENT, RelativeLayout.TRUE);

            progressWheel = new ProgressWheel(this);
            progressWheel.setBarColor(Color.GREEN);
            progressWheel.setLayoutParams(params);
            progressWheel.spin();

            rootView.addView(progressWheel);

**Comment by pnikosis** [comment]
as @gunhansancar said, you ahve to add the wheel somewhere.
