### ISSUE TITLE
Correct progress

### ISSUE THREAD

**Issue by bakoproductions** [pnikosis/materialish-progress#22]
I'm trying to test your library, but by setting progress to 0.5f I get this result 
![screenshot_2015-05-25-13-30-35](https://cloud.githubusercontent.com/assets/6217006/7796079/40eba92a-02e4-11e5-95f7-72513dd9d3eb.png).

I could try to fix this to suit my needs, but I do not have the time right now. Thanks in advance

**Comment by pnikosis** [comment]
Hi there, that´s because the progress is not set to linear. Set in the xml the valueÑ

    matProg_linearProgress="true"

And you should be set. Or in code use setLinearProgress(true)

**Comment by bakoproductions** [comment]
Of course, I missed that attribute. Thanks pnikosis
