### ISSUE TITLE
 Attributes has already been defined

### ISSUE THREAD

**Issue by AlexTereschuk** [pnikosis/materialish-progress#24]
Hi there.
After connect your library to the project appeared the following errors:
Error:(1) Attribute "titleTextStyle" has already been defined
Error:(1) Attribute "subtitleTextStyle" has already been defined
Error:(1) Attribute "divider" has already been defined
Error:(1) Attribute "background" has already been defined
Error:(1) Attribute "backgroundSplit" has already been defined
...
Error:Execution failed for task ':****:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '...\android\android-sdk\build-tools\21.1.2\aapt.exe'' finished with non-zero exit value 1

How can I fix this?
P.S.: targetSdkVersion 21, buildToolsVersion "21.1.2",

**Comment by pnikosis** [comment]
This doesn't look related with the library. These attributes are not defined here.
