### ISSUE TITLE
Adding The Progress in Toolbar Menu 

### ISSUE THREAD

**Issue by teddywest32** [pnikosis/materialish-progress#26]
I have tried to add the progress in menu but using the xml in menu doesnot shows the progress there. Also no space is found there. 

This is the refresh icon that need to be changed
![menu1](https://cloud.githubusercontent.com/assets/6309194/8203018/90ba0204-14fe-11e5-9086-fd7ecec851e7.PNG)

But i get 
![menu2](https://cloud.githubusercontent.com/assets/6309194/8203031/b15ed6ec-14fe-11e5-9e87-13b3fa8420dc.PNG)

Using the Xml doesnot give the desired output i wanted

**Comment by pnikosis** [comment]
Using the new toolbar should help you to achieve this.
