### ISSUE TITLE
How to set progress bar to stay at the value?

### ISSUE THREAD

**Issue by sadarshannaiynar** [pnikosis/materialish-progress#28]
I have a progress while for a value 60%. but the progress bar becomes fully colored after sometime i want the progress to stay at 60% how to do this?

**Comment by joeykrim** [comment]
I'm not clear on all of your comment. If you're saying that you want to set the progress to 60% and not have it change, would the .setProgress(0.6f) method accomplish your goal?

**Comment by pnikosis** [comment]
Can you elaborate on this? As @joeykrim said, with setProgress(0.6f) should be enough

**Comment by javiersuazomatus** [comment]
In my case when i want to set 50% I use setProgress(0.5f) but the progress bar represents a larger amount.

**Comment by javiersuazomatus** [comment]
In my case when i want to set 50% I use setProgress(0.5f) but the progress bar represents a larger amount.
