### ISSUE TITLE
Wheel not showing. Lacking documentation.

### ISSUE THREAD

**Issue by DannyTsegai** [pnikosis/materialish-progress#31]
I'm setting up the wheel programmatically like this:

`private ProgressWheel wheel; //global scope variable`

Within onPreExecute():

```wheel = new ProgressWheel(MainActivity.this);```
         ```   wheel.setBarColor(Color.BLUE);```
          ```  wheel.spin();```

Within onPostExecute():

`wheel.stopSpinning();`

Am I missing something? I didn't see a show() method when I was looking through ProgressWheel.java

EDIT: The docs are lacking in terms of explanation of usage. Once I get this figured out, I'll send in a pull request with some changes.

**Comment by mustafa-demir** [comment]
plus 1

**Comment by progfiles** [comment]
+1

**Comment by HassanJawed** [comment]
+ 1

**Comment by pnikosis** [comment]
Weird, I'll take a look to that issue

**Comment by pnikosis** [comment]
Check #21 for a working solution
