### ISSUE TITLE
Color issue!

### ISSUE THREAD

**Issue by MuhamedFathy** [pnikosis/materialish-progress#32]
I set the color from xml to blue but it's gives me a black wheel, also from code using `wheel.setBarColor(Color.BLUE);` but still black!

Is there anyway to fix that?!

**Comment by viniciusfmaciel** [comment]
I have a same problem

**Comment by viniciusfmaciel** [comment]
In my case, I set only in javacode and works now. Don't set the Bar Color in xml file.

**Comment by MuhamedFathy** [comment]
@viniciusfmaciel Actually i tried what you did but not works too, share your code plz.

**Comment by MuhamedFathy** [comment]
I found the solution, just define the color code from code like this 
`mWheel.setBarColor(0xFF448AFF);`
if you define the color from code but get color from xml like this it will not work
`mWheel.setBarColor(R.color.myColor);`

**Comment by pnikosis** [comment]
Yeah, it doesn't expect a color Id. Closing the issue.
