### ISSUE TITLE
progress does not show in galaxy s5 

### ISSUE THREAD

**Issue by BabakArtApps** [pnikosis/materialish-progress#34]
I implemented your library in my app and it is ok to most of devices except Samsung Galaxy s5 that runs android 4.2.2 or 5.0.0 
i do not know what is the problem, please advice me.

**Comment by pnikosis** [comment]
Can you describe the issue?

**Comment by ningbo** [comment]
maybe all the android4.2.2 devices cant work.
just cant display. And there is no error message, like u never add it
