### ISSUE TITLE
apply from: '../maven_push.gradle' not exist

### ISSUE THREAD

**Issue by 13120241790** [pnikosis/materialish-progress#36]
Hello 
I downlaod you code zip , import my ide 
show ： 
Error:(25, 0) Could not read script '/Users/zhouxuming/Downloads/materialish-progress-master/maven_push.gradle' as it does not exist.
<a href="openFile">Open File</a>

**Comment by pinguo-marui** [comment]
Just delete that line

**Comment by pnikosis** [comment]
That's right, deleting that line should do it. The maven_push.gradle is for uploading the library to the maven repo, so you shouldn't need it.
