### ISSUE TITLE
Library version 1.7 does not work with Android 6.0

### ISSUE THREAD

**Issue by VictorAlbertos** [pnikosis/materialish-progress#38]
Hi.

With Version 1.7 the ProgressWheel does not show in Android 6 devices, but it works properly with previous versions (Android 5,4…). 

But if I downgrade to previous release, version 1.5, ProgressWheel appears correctly with every Android version.

So, the problem is that using version 1.7 of your library, ProgressWheel does not show with Android 6.

I’ve used genymotion to test it: "PREVIEW: Google Nexus 5X -6.0.0 API 23-1080x1920"

Thanks!

**Comment by pnikosis** [comment]
I just tested it in Marshmallow (in a Genymotion emulator) and works correctly. Can you check if you have the animations enabled in the emulator? (in the developer options) The main change in 1.7 is that the progress wheel now follows the animation preferences.

**Comment by alashow** [comment]
Tested on Nexus 5x 6.0.1 (real device), works like a charm :)

**Comment by pnikosis** [comment]
I'm closing this as it seems its working properly.

**Comment by alashow** [comment]
I see someone is back :)
