### ISSUE TITLE
How to use this as a progress dialog

### ISSUE THREAD

**Issue by rainman20** [pnikosis/materialish-progress#39]
Hello, 
I have a progress dialog as follow:
` final ProgressDialog pd = ProgressDialog.show(this, "", "Loading...",true);`

which I call it with : 
```
if(pd!=null && pd.isShowing())
 {
    pd.dismiss();
}
```
how can I use materialish progress to replace the default progress dialog? 
thanks

**Comment by pnikosis** [comment]
You will have to create your own dialog with a layout containing the materialish progress bar.
