### ISSUE TITLE
Crash: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.pnikosis.materialishprogress.ProgressWheel$WheelSavedState

### ISSUE THREAD

**Issue by jemshit** [pnikosis/materialish-progress#50]
Crash occurs when android kills application process and tries to restore the state. i have simulated this by changing my apps storage permission to on and off, then system kills my app (or check "Dont Keep Activities" from Developer Settings). After that i returned to app and it tries to restore the state and fails with exception:

```java
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.pnikosis.materialishprogress.ProgressWheel$WheelSavedState
```

**Comment by jemshit** [comment]
I can avoid by using `android:saveEnabled="false"` on `ProgressWheel`

**Comment by pnikosis** [comment]
I'll investigate this. Thanks for the report and for the workaround.

**Comment by jemshit** [comment]
This might be problem in CustomView which hosts MaterialishProgress view, so i'm closing issue for now.
