### ISSUE TITLE
Gradle Build fails on v21\values.xml

### ISSUE THREAD

**Issue by Shadie6** [pnikosis/materialish-progress#6]
I've just downloaded your library but when I try to compile with Gradle it finish with a lot of errors (101 !)

I think that it can't find parents of Material Style, since I'm deploying on sdk 19.

Here Gradle Output:

Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugTestSources]
:app:preBuild
:app:preDebugBuild
:app:checkDebugManifest
:app:preReleaseBuild
:app:prepareComAndroidSupportAppcompatV72100Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42100Library UP-TO-DATE
:app:prepareComGithubMrengineer13Snackbar040Library UP-TO-DATE
:app:prepareComPnikosisMaterialishProgress10Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources
:app:processDebugManifest
:app:processDebugResources
D:\LAVORO\iSfa\trunk\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.0\res\values-v11\values.xml
Error:(36, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(36, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(36, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(36, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
D:\LAVORO\iSfa\trunk\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.0\res\values-v14\values.xml
Error:(9, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(9, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(9, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(9, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
D:\LAVORO\iSfa\trunk\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.0\res\values-v21\values.xml
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Body1'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Body2'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Button'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Caption'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display1'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display2'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display3'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display4'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Headline'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Inverse'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Large'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Large.Inverse'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Large'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Small'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Medium'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Medium.Inverse'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Menu'.
Error:Error retrieving parent for item: No resource found that matches the given name '@android:TextAppearance.Material.SearchResult.Subtitle'.
Error:Error retrieving parent for item: No resource found that matches the given name '@android:TextAppearance.Material.SearchResult.Title'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Small'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Small.Inverse'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Subhead'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Title'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Menu'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle.Inverse'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title.Inverse'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionMode.Subtitle'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionMode.Title'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Large'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Small'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Button'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.ActionBar'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.Dark'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.Dark.ActionBar'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.Light'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionBar.TabText'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionBar.TabView'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton.CloseMode'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton.Overflow'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.AutoCompleteTextView'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.DropDownItem.Spinner'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabText'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabText'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabView'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.AutoCompleteTextView'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.PopupMenu'.
Error:(298, 21) No resource found that matches the given name: attr 'android:overlapAnchor'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListPopupWindow'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListView.DropDown'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListView'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.PopupMenu'.
Error:(298, 21) No resource found that matches the given name: attr 'android:overlapAnchor'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ProgressBar'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ProgressBar.Horizontal'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Toolbar.Button.Navigation'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Dialog'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light'.
Error:Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light.Dialog'.
Error:(144, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(146, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(147, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(145, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(142, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(143, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(144, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(146, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(147, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(145, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(142, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(143, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(144, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(146, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(147, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(145, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(142, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(143, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(144, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(146, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(147, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(145, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(142, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(143, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     C:\Users\Luca\sdk\build-tools\19.1.0\aapt.exe package -f --no-crunch -I C:\Users\Luca\sdk\platforms\android-19\android.jar -M D:\LAVORO\iSfa\trunk\app\build\intermediates\manifests\debug\AndroidManifest.xml -S D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug -A D:\LAVORO\iSfa\trunk\app\build\intermediates\assets\debug -m -J D:\LAVORO\iSfa\trunk\app\build\generated\source\r\debug -F D:\LAVORO\iSfa\trunk\app\build\intermediates\libs\app-debug.ap_ --debug-mode --custom-package it.gn.sfa -0 apk --output-text-symbols D:\LAVORO\iSfa\trunk\app\build\intermediates\symbols\debug
> Error Code:
>     1
> Output:
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:7: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:9: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Body1'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:11: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Body2'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:13: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Button'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:15: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Caption'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:17: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display1'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:19: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display2'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:21: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display3'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:23: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display4'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:25: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Headline'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:27: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Inverse'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:29: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Large'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:31: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Large.Inverse'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:33: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Large'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:35: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Small'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:37: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Medium'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:39: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Medium.Inverse'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:41: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Menu'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:43: error: Error retrieving parent for item: No resource found that matches the given name '@android:TextAppearance.Material.SearchResult.Subtitle'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:45: error: Error retrieving parent for item: No resource found that matches the given name '@android:TextAppearance.Material.SearchResult.Title'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:47: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Small'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:49: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Small.Inverse'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:51: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Subhead'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:53: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Title'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:55: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Menu'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:57: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:59: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle.Inverse'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:61: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:63: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title.Inverse'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:65: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionMode.Subtitle'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:67: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionMode.Title'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:69: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Large'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:71: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Small'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:73: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Button'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:75: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:77: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v11\values.xml:39: error: Error: No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v14\values.xml:12: error: Error: No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v11\values.xml:46: error: Error: No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v14\values.xml:20: error: Error: No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v11\values.xml:53: error: Error: No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v14\values.xml:28: error: Error: No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v11\values.xml:60: error: Error: No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v14\values.xml:36: error: Error: No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:87: error: Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:89: error: Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.ActionBar'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:93: error: Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.Dark'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:100: error: Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.Dark.ActionBar'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:108: error: Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.Light'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:267: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionBar.TabText'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:269: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionBar.TabView'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:271: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:273: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton.CloseMode'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:275: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton.Overflow'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:285: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.AutoCompleteTextView'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:287: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.DropDownItem.Spinner'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:289: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabText'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:291: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabText'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:293: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabView'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:295: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.AutoCompleteTextView'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:297: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.PopupMenu'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:301: error: Error: No resource found that matches the given name: attr 'android:overlapAnchor'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:304: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListPopupWindow'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:306: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListView.DropDown'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:308: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListView'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:310: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.PopupMenu'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:314: error: Error: No resource found that matches the given name: attr 'android:overlapAnchor'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:317: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ProgressBar'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:319: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ProgressBar.Horizontal'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:321: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:323: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:329: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Toolbar.Button.Navigation'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:331: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:336: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Dialog'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:341: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:346: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light.Dialog'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:147: error: Error: No resource found that matches the given name: attr 'android:colorAccent'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:149: error: Error: No resource found that matches the given name: attr 'android:colorControlActivated'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:150: error: Error: No resource found that matches the given name: attr 'android:colorControlHighlight'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:148: error: Error: No resource found that matches the given name: attr 'android:colorControlNormal'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:145: error: Error: No resource found that matches the given name: attr 'android:colorPrimary'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:146: error: Error: No resource found that matches the given name: attr 'android:colorPrimaryDark'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:185: error: Error: No resource found that matches the given name: attr 'android:colorAccent'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:187: error: Error: No resource found that matches the given name: attr 'android:colorControlActivated'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:188: error: Error: No resource found that matches the given name: attr 'android:colorControlHighlight'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:186: error: Error: No resource found that matches the given name: attr 'android:colorControlNormal'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:183: error: Error: No resource found that matches the given name: attr 'android:colorPrimary'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:184: error: Error: No resource found that matches the given name: attr 'android:colorPrimaryDark'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:223: error: Error: No resource found that matches the given name: attr 'android:colorAccent'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:225: error: Error: No resource found that matches the given name: attr 'android:colorControlActivated'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:226: error: Error: No resource found that matches the given name: attr 'android:colorControlHighlight'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:224: error: Error: No resource found that matches the given name: attr 'android:colorControlNormal'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:221: error: Error: No resource found that matches the given name: attr 'android:colorPrimary'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:222: error: Error: No resource found that matches the given name: attr 'android:colorPrimaryDark'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:261: error: Error: No resource found that matches the given name: attr 'android:colorAccent'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:263: error: Error: No resource found that matches the given name: attr 'android:colorControlActivated'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:264: error: Error: No resource found that matches the given name: attr 'android:colorControlHighlight'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:262: error: Error: No resource found that matches the given name: attr 'android:colorControlNormal'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:259: error: Error: No resource found that matches the given name: attr 'android:colorPrimary'.
>     D:\LAVORO\iSfa\trunk\app\build\intermediates\res\debug\values-v21\values.xml:260: error: Error: No resource found that matches the given name: attr 'android:colorPrimaryDark'.
> Information:BUILD FAILED
> Information:Total time: 40.624 secs
> Information:101 errors
> Information:0 warnings
> Information:See complete output in console

I have to put sdk 21 as base sdk or I could deploy on 19 one?

**Comment by AndroidNinza** [comment]
[Here](https://github.com/facebook/react-native/issues/10367) is the solution for this
