### ISSUE TITLE
Multicolored Rim

### ISSUE THREAD

**Issue by androlizer** [pnikosis/materialish-progress#9]
Any plan to add, multicolored rim as can be seen in Google Inbox app?

**Comment by pnikosis** [comment]
So far, no. I would have to think a little how to implement it without adding too much complexity, I will take a look though.

**Comment by androlizer** [comment]
It'll be great, thanks we're facing one more issue the rotation slows down
when used on same screen again and again. You might have aware of it, if
possible tell us any workaround

**Comment by pnikosis** [comment]
I wasn't aware about that one, can you give me an example on how to reproduce it? Thanks!

About the multicolored progress, also you can try by changing the color of the progress manually as well.

**Comment by androlizer** [comment]
I'll provide u with a video of this issue asap, or if u've time u can look
our app at play store it has the issue, search for any trailer again and
for two three times, u can download app here
http://play.google.com/store/apps/details?id=com.appskart.teasersntrailers,
thanks for ur response.

I wasn't aware about that one, can you give me an example on how to
reproduce it? Thanks!

About the multicolored progress, also you can try by changing the color of
the progress manually as well.

--
Reply to this email directly or view it on GitHub
<https://github.com/pnikosis/materialish-progress/issues/9#issuecomment-69759073>
.

**Comment by pnikosis** [comment]
Duplicated from this one, maybe fixed

https://github.com/pnikosis/materialish-progress/issues/13
